FORMAT: 1A
HOST:  https://eservant.quidinfo.it


# Core services

Microservizio che offre le funzionalità core di eServant.

# Group Events  

## /core/events 

### GET

Ritorna la lista di tutti gli eventi memorizzati nel sistema. 
La richiesta non ha vincoli particolari di formato. 

+ Request (application/json)

+ Response 200 (application/json)

 + Attributes (CEEventListRes)
 

## /core/events/{id}

[***STABLE***]

### GET

Restituisce il dettaglio dell'evento corrispondente all' `id` passato.

Se l'id passato non esiste ritorna un errore.

+ Parameters
    + id (number, required) - identificativo dell'evento 

+ Request (application/json)
    + Parameters
        + id: 2
        
+ Response 200 (application/json)

    + Attributes (CEEventRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)


## /core/events/users/{username} 

[***STABLE***]
      
### GET 

Ritorna gli eventi correnti o futuri associati all'utente.
Componendo invece una request priva di username parameter o non ancora registrato al sistema, viene ritornato un messaggio d'errore, ad ora, generico.

+ Parameters
    + username - username dell'utente di cui si intende reperire gli eventi 

+ Request (application/json)
    + Parameters
        + username: rossi.mario@gmail.com

+ Response 200 (application/json)

    + Attributes (CEEventUserListRes)

+ Response 500 (application/json)
    
    + Attributes (CE230Error)

## /core/events/suggestions

[***STABLE***]

### GET

Restituisce la lista dei ***primi 10*** eventi ordinati in base ad un algoritmo basato sull'importanza dell'evento.
I parametri che costituiscono il filtro degli eventi sono: `shortname`, `eventAggregator`, `timeFrom` e `timeTo`.


+ Attributes
    + Shortname: "Master in IoT" (string, required) - nome dell'evento 
    + EventAggregator: "Corso di laurea" (string, optional) - tipo di evento
    + Timefrom: `2018-10-01T08:30:00.603Z` (string, optional) - ora di inizio
    + Timeto: `2018-10-12T15:30:00.603Z` (string, optional) - ora di fine

+ Response 200 (application/json)

    + Attributes (CESuggestedEventListRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)

## /core/associate/events/{id}/users/{username}

[***STABLE***]

### PUT

Associa l'evento, il cui `id` è fornito in input, allo user, con `username` passato.
Ritorna i dati dell'evento appena associato. 


+ Parameters
    + id: 80677375 (number, required) - identificativo dell'evento che si intende associare all'utente
   
    + username: cj@quidinfo.it (string, required) - identificativo dell'utente che si intende 
                                                    associare all'evento
    
+ Request (application/json)

    + Parameters
        + username: cj@quidinfo.it 
        + id: 80677375
        
+ Response 200 (application/json)
    
     + Attributes (CEEventRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)

## /core/share/events/{id}/users/{username}

[***STABLE***]

### PUT

Memorizza dati della condivisione dell'evento `id` sul profilo social di user `username`. 

+ Parameters
    + id: 80677375 (number, required) - identificativo dell'evento
   
    + username: cj@quidinfo.it (string, required) - identificativo dell'utente che esegue la 
                                                    condivisione
                                                    
+ Request (application/json)

    + Parameters
        + username: cj@quidinfo.it 
        + id: 80677375

    + Attributes(CESocialNameReq)
    
+ Response 200 (application/json)
    
     + Attributes (CEEventRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)

# Group Notifications

## /core/notifications 

[***STABLE***]

### GET

Ritorna la lista di tutte le notifiche. 

+ Response 200 (application/json)

     + Attributes (CENotificationListRes)


## /core/notification-actions/{id}

[***STABLE***]

### PUT 

Processa operazione richiesta il cui `id` è passato in input, ritornando `payload` in input. 

+ Parameters
    + id - identificativo dell' azione da effettuare, in risposta di una notifica 

+ Request (application/json)
    + Parameters
        + id: 10
    + Attributes (CENotificationActionReq)
        
+ Response 200 (application/json)

    + Attributes (CENotificationActionRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)


# Group Facilities

## /core/facilities

[***STABLE***]

### GET

Ritorna la lista di tutti gli impianti.

+ Response 200 (application/json)
  
    + Attributes (CEFacilityListRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)


## /core/facilities/{id}

[***STABLE***]
      
### GET 

Ritorna il dettaglio della facility identificata da `id` in input.

+ Parameters
    + id - identificativo della facility che si necessita 

+ Request (application/json)
    + Parameters
        + id: 80677375

+ Response 200 (application/json)

    + Attributes (CEFacilityRes)
        
+ Response 500 (application/json)

 + Attributes (CE230Error)

## /core/follow/facilities/{id}/users/{username}

[***STABLE***]

### PUT

Associa tutti gli eventi, attuali e futuri, della facility, corrispondente ad `id`,
allo user, specificato da `username`. Ritorna la lista degli eventi associati alla facility.

+ Parameters
    + id: 80677375 (number, required) - identificativo dell'impsianto che viene associato all'utente
   
    + username: cj@quidinfo.it (string, required) - identificativo dell'utente a cui l'impianto, 
                                                    cioè tutti i suoi eventi, viene associato
    
+ Request (application/json)
    + Parameters
        + username: cj@quidinfo.it 
        + id: 80677375

+ Response 200 (application/json)

    + Attributes (CEEventListRes)
    
+ Response 500 (application/json)

 + Attributes (CE230Error)

# Group Agenda

## /core/agenda/events/{id}

[***STABLE***]

### GET

Restituisce il programma di un evento.
Il campo 'id' nella request è obbligatoria.

Il programma dell'evento è formato da:
* Una data di inizio e una data di fine espresso nel formato ISO-8601 dove è valorizzata solo la data e non l'orario,
* Una lista di TimeSlots che rappresentano le varie attività svolte in tutta la durata dell'evento.
  * **TimeSlot**, singola attività nel programma di un evento
    + timeFrom: 2017-04-14T08:21:45.484+0000 (string, required) - qui è l'orario ad essere valorizzato
    + timeTo: 2017-04-14T08:23:45.484+0000 (string, required) - qui è l'orario ad essere valorizzato
    + shortName: corso di cucina (string, required) - nome attività
    + text: corso di cucina giapponese,... (string, optional) - descrizione
    + pic: 648521f1-fe15-4408-b489-0cecbcd97e76.png (string, optional) - immagine attività
  * Se devo esprimere un'eccezione su un TimeSlot allora nella lista dei TimeSlot ne sarà presente anche uno con gli attributi exception e fatherId valorizzati, dove fatherId è l'id del TimeSlot in cui si verifica l'eccezione e exception è una stringa che spiega l'eccezione,
* Un attributo dayOfWeek che se valorizzato indica che l'evento è ricorrente,
* Gli attributi fatherId ed exception che sono valorizzati sse devo esprimere un'eccezione sul programma, sarà quindi presente un secondo programma che avrà come fatherId il programma in cui va generata l'eccezione.

+ Parameters
    + id: 24146414 (number, required) - identificativo del programma di evento che si necessita 

+ Request (application/json)
    + Parameters
        + id: 24146414 (number, required)

+ Response 200 (application/json)

    + Attributes (CEAgendaRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)


# Group Services

## /core/services/

### GET

Restituisce i services generici.

Normalmente questi servizi sono tutti di categoria *help*.

+ Response 200 (application/json)
  
    + Attributes (CEServiceGenericSummaryListRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)

## /core/services/{serviceId}

### GET

Restituisce informazioni dettagliate sul servizio corrispondente a `serviceId`.

Ogni servizio ha:
* una privacy associata, da 10 a 50 dove 10 rappresenta nessuna privacy e 50 massima privacy. Il servizio è fruibile solo se l'utente ha accettato un livello di privacy uguale o superiore a quello richiesto
*  una action associata. I tipi di action si distinguono per la proprietà command, da cui derivano le proprietà 'data' richieste:
   * **tel**, telefona
      + shortName: Carabinieri (string, required)
      + command: tel (string, required)
      + data: 
          + phone: 999 (string, required)
   * **sms**, invia sms con testo precompilato
      + command: sms (string, required)
      + data:
          + phone: 366654 (string, required)
          + messaggio: Ciao, sono al concerto di Gianni Morandi! (string, required)
   * **surf**, apri il browser su pagina web
      + command: surf (string, required)
      + data:
          + url: https://google.com (string, required)
   * **share**, share testo
      + command: share (string, required) 
      + data:
          + text: Covo dei Golosi via ponte a Giogoli Firenze (string, required)
          + url: https://google.com (string, optional)
   * **goto**, indicazioni su come raggiungere un servizio. Ritorna una url corrispondente ad una mappa ed, eventualmente, un warning nel caso sia richiesta la localizzazione del dispositivo (es. fotografando barcode)
      + command: goto (string, required) 
      + data:
          + url: http://eservant-sviluppo:8100/map/buildings/1 (string, required) url per richiedere la mappa con i POI da mostrare


+ Parameters
    
    + serviceId: 82132332 (number, required) - identificativo del servizio di cui si cerca dettaglio

+ Response 200 (application/json)
   
    + Attributes (CEServiceDetailRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)

## /core/services/events/{eventId}

### GET

Restituisce i servizi associati all'evento corrispondente a `eventId`. 

Nota bene: un aiuto è da intendersi come un servizio di una particolare categoria (*help*). 

+ Parameters
    
    + eventId: 80677375 (number, required) - identificativo dell'evento a cui sono associati i servizi cercati


+ Response 200 (application/json)
   
    + Attributes (CEServiceSummaryListRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)


# Group QR Position

## /core/set-qr-position

### POST

* Questo servizio viene usato quando occorre settare la posizione via qrcode.
* L'utente può quindi scansionare un QrCode inviando così una request al server con i seguenti parametri:
  * **poiId**: id del Poi in cui è posto il QrCode
  * **deviceToken**: id del dispositivo che ha fatto la scansione del QrCode

+ Parameters
   + poiId (number,required) - identificativo del poi
   + deviceToken (string, required) - identificativo del telefono

+ Request (application/json)
    + Parameters
        + poiId (number, required) 
        + deviceToken (string, required)

+ Response 200 (application/json)
    
  + Attributes (CEPositionRes) 
  
+ Response 500 (application/json)
  
   + Attributes (CEServerError)

# Group News  

## /core/news

### GET

Ritorna tutte le news presenti.

+ Request (application/json)

+ Response 200 (application/json)

 + Attributes (CENewsListRes)


## /core/news/{id}

### GET

Ritorna la news corrispondente all' `id` passato.

Se l'id passato non esiste ritorna un errore.

+ Parameters
    + id (number, required) - identificativo dell'evento 

+ Request (application/json)
    + Parameters
        + id: 2
        
+ Response 200 (application/json)

    + Attributes (NewsRes)

+ Response 500 (application/json)

 + Attributes (CE230Error)

 

## Data Structures

### CEEventReq
+ metadata (MessagesSuccess)
+ payload (EventShareReq)

### CEEventRes
+ metadata (MessagesSuccess)
+ payload (EventRes)

### CEEventListRes
+ metadata (MessagesSuccess)
+ payload (array[EventRes, EventRes1])

### CESuggestedEventListRes
+ metadata (MessagesSuccess)
+ payload (array[EventSuggested, EventSuggested1])

### CEEventUserListRes
+ metadata (MessagesSuccess)
+ payload (array[EventFacSummaryRes, EventFacSummaryRes1])

### CENotificationListRes
+ metadata (MessagesSuccess)
+ payload (array[NotificationRes, NotificationRes1])

### CENotificationActionReq
+ metadata (MessagesSuccess)
+ payload (NotificationActionReq)

### CENotificationActionRes
+ metadata (MessagesSuccess)
+ payload (NotificationActionRes)

### CEFacilityRes
+ metadata (MessagesSuccess)
+ payload (FacilityRes)

### CEFacilityListRes
+ metadata (MessagesSuccess)
+ payload (array[FacilityRes, FacilityRes1])

### CEAgendaRes
+ metadata (MessagesSuccess)
+ payload (array[AgendaRes])

### CEServiceGenericSummaryListRes
+ metadata (MessagesSuccess)
+ payload (array[ServiceGenericSummaryRes, ServiceGenericSummaryRes1])

### CEServiceSummaryListRes
+ metadata (MessagesSuccess)
+ payload (array[ServiceSummaryRes, ServiceSummaryRes1])

### CEServiceDetailRes
+ metadata (MessagesSuccess)
+ payload (ServiceDetailRes)

### CESocialNameReq
+ metadata (MessagesSuccess)
+ payload (SocialNameReq)

### CENewsListRes
+ metadata (MessagesSuccess)
+ payload (NewsRes)


### CEPositionRes
+ metadata (MessagesSuccess)
+ payload (PositionRes)

### MessagesSuccess
+ messages (array[string]) - Nessun messaggio di errore


### id1
+ id: 1 (number, required)

### id2
+ id: 2 (number, required)


### EventRes
+ id: 78869707 (number, required) - identificatore evento
+ shortName:  Corso di Master in IoT (string, required) - nome evento
+ smallPic: `648521f1-fe15-4408-b489-0cecbcd97e76.png` (string, optional) - uuid immagine (formato piccolo) evento in NAS (Network Attached Storage)
+ bigPic: `2431521f1-fe15-4408-b489-0cecbcd9773.png` (string, optional) - uuid immagine (formato grande) evento in NAS (Network Attached Storage)
+ text: Il corso ha lo scopo di introdurre gli studenti ai seguenti argomenti... (string, required) - descrizione dell'evento
+ isSpot: true (boolean, required) - indica se ha calendario finito (conferenza o concerto)
+ startTS: `2018-09-01T10:22:43.235+0000` (string, required) - data inizio evento (ridondata con Agenda)
+ endTS: `2018-09-01T10:22:43.235+0000` (string, required) - data fine evento (ridondata con Agenda)
+ facilityId: 12345678 (number, required) - id impianto
+ aggregationFields: (array[enum[string]], required) - aggregatori di eventi
    + Members
        + `VIVI_IL_PIN`
        + `MUSICA_CLASSICA`
        + `MUSICA_ROCK`

### EventRes1
+ id: 21345678 (number, required) - identificatore evento
+ shortName:  Vivi il PIN (string, required) - nome evento
+ smallPic: `648521f1-fe15-4408-b489-0cecbcd97e76.png` (string, optional) - uuid immagine (formato piccolo) evento in NAS (Network Attached Storage)
+ bigPic: `648521f1-fe15-4408-b489-0cecbcd9773.png` (string, optional) - uuid immagine (formato grande) evento in NAS (Network Attached Storage)
+ text: L'evento ha lo scopo di... (string, required) - descrizione dell'evento
+ isSpot: true (boolean, required) - indica se ha calendario finito (conferenza o concerto)
+ startTS: `2018-09-01T10:22:43.235+0000` (string, required) - data inizio evento (ridondata con Agenda)
+ endTS: `2018-09-01T10:22:43.235+0000` (string, required) - data fine evento (ridondata con Agenda)
+ facilityId: 12345678 (number, required) - id impianto
+ aggregationFields: (array[enum[string]], required) - aggregatori di eventi
    + Members
        + `VIVI_IL_PIN`

### EventSuggested
+ isFollow: true (boolean, required) - partecipazione dello user all'evento
+ event(EventRes) 

### EventSuggested1
+ isFollow: true (boolean, required) - partecipazione dello user all'evento 
+ event(EventRes1) 


### EventFacSummaryRes
+ id: 78869707 (number, required) - identificatore evento
+ shortName:  Corso di Master in IoT (string, required) - nome evento
+ smallPic: `648521f1-fe15-4408-b489-0cecbcd97e76.png` (string, optional) - uuid immagine (formato piccolo) evento in NAS (Network Attached Storage)
+ bigPic: `4b58bc09-8630-4a8f-ab10-3a230df72369.jpeg` (string, required) - uuid immagine (formato grande) evento in NAS (Network Attached Storage)
+ text: Il corso ha lo scopo di introdurre gli studenti ai seguenti argomenti... (string, required) - descrizione dell'evento
+ isSpot: true (boolean, required) - indica se ha calendario finito (conferenza o concerto)
+ startTS: `2018-09-01T10:22:43.235+0000` (string, required) - data inizio evento (ridondata con Agenda)
+ facility: (FacilitySummaryRes, required) - info riassuntive della facility

### EventFacSummaryRes1
+ id: 12345678 (number, required) - identificatore evento
+ shortName:  Vivi il PIN (string, required) - nome evento
+ smallPic: `648521f1-fe15-4408-b489-0cecbcd97e76.png` (string, optional) - uuid immagine (formato piccolo) evento in NAS (Network Attached Storage)
+ bigPic: `4b58bc09-8630-4a8f-ab10-3a230df72369.jpeg` (string, required) - uuid immagine (formato grande) evento in NAS (Network Attached Storage)
+ text: Il corso ha lo scopo di introdurre gli studenti ai seguenti argomenti... (string, required) - descrizione dell'evento
+ isSpot: true (boolean, required) - indica se ha calendario finito (conferenza o concerto)
+ startTS: `2018-09-01T10:22:43.235+0000` (string, required) - data inizio evento (ridondata con Agenda)
+ facility: (FacilitySummaryRes1, required) - info riassuntive della facility

### EventAggregatorRes
+ id : 12 (number, required)
+ type : sport (string, required)

### EventAggregatorRes1
+ id : 10 (number, required)
+ type : intrattenimento (string, required)


### EventShareReq
+ socialId: Facebook (string, required) - identificatore del social
+ id: 78869707 (number, required) - identificatore evento
+ shortName:  Corso di Master in IoT (string, required) - nome evento
+ smallPic: `6dffe2ad-5c8a-4065-af89-9ca3694a87c6.png` (string, optional) - uuid ad immagine piccola evento in NAS (Network Attached Storage)
+ bigPic: `846dfa1e-c5f8-44db-8410-cf4eb8d147ab.jpeg` (string, required) - uuid ad immagine grande evento in NAS (Network Attached Storage)
+ text: Il corso ha lo scopo di introdurre gli studenti ai seguenti argomenti... (string, required) - descrizione dell'evento
+ facilityId: 69298237 (number, required) - identificatore di impianto
+ isSpot: true (boolean, required) - booleano che indica se ha calendario finito (conferenza o concerto)
+ startTS: `2018-09-01T10:22:43.235Z` (string, required) - data inizio evento
+ calendarId: 50491071 (number, required) - identificatore del calendario dell'evento
+ eventType: educazione (string, required) - tipologia di evento
+ creationTS: `2018-09-01T10:22:43.235Z` (string, required) - data generazione evento

### PoiEvFacRes
+ id: 1 (number, required) - id Point Of Interest
+ shortName: Entrata 1 (string, required) - nome POI
+ text: Entrata nord-ovest (string, optional) - descrizione del POI
+ latitude: 23.2 (number, required) - latitudine
+ longitude: 635.2 (number, required) - longitudine
+ level: 2 (number, required) - piano 
+ isAccessible: true (boolean) - accessibilità per invalidi
+ isActive: true (boolean, required) - stato del POI (operativo o meno)
+ creationTS: `2018-11-05T19:04:15.735+0000` (string, required) - data di creazione del POI
+ poiType: 1232 (number, required) - tipologia di POI

### PoiEvFacRes1
+ id: 2 (number, required) - id Point Of Interest
+ shortName: Varco (string, required) - nome POI
+ text: Varco sud-est (string, optional) - descrizione del POI
+ latitude: 23.2 (number, required) - latitudine
+ longitude: 635.2 (number, required) - longitudine
+ level: 2 (number, required) - piano 
+ isAccessible: true (boolean) - accessibilità per invalidi
+ isActive: true (boolean, required) - stato del POI (operativo o meno)
+ creationTS: `2018-11-05T19:04:15.735+0000` (string, required) - data di creazione del POI
+ poiType: 1232 (number, required) - tipologia di POI


### PositionRes
+ id: 378249 (number, required) - id del poi 
+ latitude: 27.3 (number, required) - latitudine
+ longitude: 35.564 (number, required) - longitudine
+ level: 1 (number, required) - piano o livello
+ deviceToken: 'fOIT6h15i7U:APA91bE90sn87vqvUQv2eMWcKA0z626Bz-ypCI-J_I5f3gWEIr7ISLqE1qZszSGWOcNF-EcO3yiCf5mWv6-S5sTBB4oa916lhpd_6oSFGDMo5UU-4LnXYFkAOR8bLDQdBp0a6EB8M3f0' (string, required) 
+ measureTS: `2018-11-05T19:04:15.735+0000` (string, required) - data di associazione utente-posizione


### NotificationRes

+ id: 80768151 (number, required) - identificatore notifica
+ priority: 4 (number, required) - priorità di notifica
+ shortName: Coda su A1 (string, required) - nome notifica
+ text: Si prevede una coda di... (string, required) - descrizione
+ creationTS: `2018-11-05T19:04:15.735+0000` (string) - data di generazione della notifica
+ mainTS: `2018-11-05T30:04:15.735+0000` (string) - data di inizio (evento o altro)
+ order: 4 (number, required) - mappa un certo tipo di ordinamento per la visualizzazione delle notifiche da definire meglio con FE
+ group: traffico (string, required) - categoria della notifica
+ actionCategory: clicca qui (string, optional) - azione associabile alla notifica, ad esempio rispondi si o reply ad un messaggio o link TODO tipizzare
+ actionActivityId: 123 (number, optional) - serve per richiamare il servizio /core/notificationAction/{id} che riporta la risposta all'azione associata alla notifica
+ actionLink:  https://www.autostrade.it (string, optional) - eventuale link da aprire sul modulo web interno o direttamente su browser, dipende da come funziona ionic

### NotificationRes1

+ id: 123345678 (number, required) - identificatore notifica
+ priority: 1 (number, required) - priorità di notifica
+ shortName: Emergenza: incendio (string, required) - nome notifica
+ text: L'incendio ha colpito il settore... (string, required) - descrizione
+ creationTS: `2018-11-05T19:04:15.735+0000` (string) - data di generazione della notifica
+ mainTS: `2018-11-05T30:04:15.735+0000` (string) - data di inizio (evento o altro)
+ order: 1 (number, required) - mappa un certo tipo di ordinamento per la visualizzazione delle notifiche da definire meglio con FE
+ group: emergenza (string, required) - categoria della notifica




### NotificationActionReq
+ body: param1, param2, param3 (string, optional) - parametri da passare all'azione

### NotificationActionRes
+ id: 10 (number, required) - identificatore della notification action passata in input
+ body: param1 param2 param3 (string, optional) - parametri di input della action passati nella `request`



### FacilityRes
+ id: 80677375 (number, required) - identificativo dell'impianto
+ shortName: Stadio Artemio Franchi (string, required) - nome impianto
+ pic: `06d7767b-81ae-480b-849b-0340f9ae1918.jpeg` (string, required) - uuid ad immagine impianto in NAS (Network Attached Storage)
+ text: stadio di Firenze (string, required) - descrizione dell'impianto
+ owner: Pippo (string, required) - intestatario dell'impianto
+ creationTS: `2018-09-01T10:22:43.235+0000` (string, required) - data generazione impianto
+ pof: (PofRes, required) - POI of facility, poi che coincide con sede legale della facility
+ pois (array[id1, id2]) 
+ facilitiesAggregator: (array[FacilityAggregatorRes, FacilityAggregatorRes1], required) - aggregatori Facility

### FacilityRes1
+ id: 98765432 (number, required) - identificativo dell'impianto
+ shortName: PIN (string, required) - nome impianto
+ pic: `06d7767b-81ae-480b-849b-0340f9ae1918.jpeg` (string, required) - uuid ad immagine impianto in NAS (Network Attached Storage)
+ text: stadio di Firenze (string, required) - descrizione dell'impianto
+ owner: Pippo (string, required) - intestatario dell'impianto
+ creationTS: `2018-09-01T10:22:43.235+0000` (string, required) - data generazione impianto
+ pof : (PofRes, required) - POI of facility, poi che coincide con sede legale della facility
+ pois: (array[id1, id2])
+ facilitiesAggregator: (array[FacilityAggregatorRes, FacilityAggregatorRes1], required) - aggregatori Facility

### FacilityAggregatorRes
+ id: 1 (number, required) - identificativo dell'aggregatore
+ type: SPORT (string, required) - tipo dell'aggregatore

### FacilityAggregatorRes1
+ id: 2 (number, required) - identificativo dell'aggregatore
+ type: MUSIC (string, required) - tipo dell'aggregatore

### FacilitySummaryRes
+ id: 80677353 (number, required) - identificativo dell'impianto
+ shortName: Università degli studi di Firenze (string, required) - nome impianto

### FacilitySummaryRes1
+ id: 80677369 (number, required) - identificativo dell'impianto
+ shortName: PIN (string, required) - nome impianto


### PofRes
+ id: 3 (number, required) - id Point Of Facility
+ shortName: Sede legale (string, required) - nome POF
+ text: Indirizzo della sede legale  (string, optional) - descrizione del POF
+ latitude: 23.2 (number, required) - latitudine
+ longitude: 635.2 (number, required) - longitudine
+ level: 0 (number, required) - piano 
+ isAccessible: true (boolean) - accessibilità per invalidi
+ isActive: true (boolean, required) - stato del POF (operativo o meno)
+ creationTS: `2018-11-05T19:04:15.735+0000` (string, required) - data di creazione del POF
+ poiType: 1232 (number, required) - tipologia di POF


### AgendaRes 
+ id: 18869708 (number, required) - identificatore del programma
+ startDate: `2017-04-14T08:21:45.484+0000` (string, required) - data (no time) inizio evento ISO datetime
+ endDate: `2017-04-14T08:21:45.484+0000` (string, required) - data (no time) fine evento ISO datetime
+ timeSlots: (array[TimeSlotRes, TimeSlotRes1]) - time slot riferibili al calendario corrente


### AgendaExceptionRes 
+ id: 28869708 (number, required) - identificatore del programma
+ startDate: `2017-04-14T08:21:45.484+0000` (string, required) - data (no time) inizio evento ISO datetime
+ endDate: `2017-04-14T08:21:45.484+0000` (string, required) - data (no time) fine evento ISO datetime
+ exception: eccezione che cancella l'intero programma (string, required)
+ fatherId: 18869708 (number, required) - identificatore del programma su cui generare l'eccezione

### AgendaServiceRes 
+ id: 78869708 (number, required) - identificatore del programma
+ startDate: `2017-04-14T08:21:45.484+0000` (string, required) - data (no time) inizio evento ISO datetime
+ endDate: `2017-04-14T08:21:45.484+0000` (string, required) - data (no time) fine evento ISO datetime
+ dayOfWeek: MO (string, optional) valorizzato se evento ricorrente
+ exception: chiusura straordinaria (string, optional) - eventuale eccezione sul calendario
+ fatherId: 8492032 (number, optional) - id di una agenda da cui deriva questa. valorizzato sse valorizzata l'eccezione
+ timeSlots: (array[TimeSlotRes, TimeSlotRes1]) - time slot riferibili al calendario corrente



### TimeSlotRes
+ id: 78869708 (number, required) - timeSlot id
+ timeFrom: `2017-04-14T08:21:45.484+0000` (string, required) - ISO date-time di inizio timeSlot. Se dayOfWeek valorizzato considerare solo la parte time
+ timeTo: `2017-04-14T08:23:45.484+0000` (string, required) - ISO date-time di fine timeSlot. Se dayOfWeek valorizzato considerare solo la parte time
+ shortName: primo (string, required) - short name dello slot
+ text: `Fiorentina-Roma` (string, optional) - descrizione del timeSlot
+ pic: `37adab3a-c008-4fc1-9e72-cb28383a31d5.jpeg` (string, required) - uuid ad immagine

### TimeSlotRes1
+ id: 12345678 (number, required) - timeSlot id
+ fatherId: 78869708 (number) - father timeslot id
+ timeFrom: `20182017-04-14T08:21:45.484+0000` (string, required) - ISO date-time di inizio timeSlot. Se dayOfWeek valorizzato considerare solo la parte time
+ timeTo: `2017-04-14T08:21:45.484+0000` (string, required) - ISO date-time di fine timeSlot. Se dayOfWeek valorizzato considerare solo la parte time
+ exception: campo inutilizzabile per maltempo (string) - eventuale eccezione sullo slot
+ shortName: primo (string, required) - short name dello slot
+ text: `Fiorentina-Roma` (string, optional) - descrizione del timeSlot
+ pic: `37adab3a-c008-4fc1-9e72-cb28383a31d5.jpeg` (string, required) - uuid ad immagine


### ServiceGenericSummaryRes
+ id: 123 (number, required) - identificatore del servizio
+ shortName: SOS (string, required) - nome del servizio
+ pic: `polizia` (string, required) - uuid immagine (icona) rappresentante il servizio
+ text: Chiamate di emergenza (string, optional) - descrizione del servizio
+ isActive: true (boolean, required) - se il servizio è attivo (operativo o meno)
+ isGeneric: true (boolean, required) - se il servizio è generico
+ category: help (string, required) tipologia di servizio. Nota bene: un aiuto è da intendersi come un servizio di una 
particolare categoria (*help*). Dunque il tapping sull'icona aiuto dovrà chiamare questo servizio
con `category:help`. 

### ServiceGenericSummaryRes1
+ id: 124 (number, required) - identificatore del servizio
+ shortName: SOS (string, required) - nome del servizio
+ pic: `vigili_fuoco` (string, required) - uuid immagine (icona) rappresentante il servizio
+ text: Chiamate di emergenza (string, optional) - descrizione del servizio
+ isActive: true (boolean, required) - se il servizio è attivo (operativo o meno)
+ isGeneric: true (boolean, required) - se il servizio è generico
+ category: help (string, required) tipologia di servizio

### ServiceSummaryRes
+ id: 456 (number, required) - identificatore del servizio
+ shortName: Punto di ristoro (string, required) - nome del servizio
+ pic: `caffe` (string, required) - uuid immagine (icona) rappresentante il servizio
+ text: Caffè, tavola calda (string, optional) - descrizione del servizio
+ isActive: true (boolean, required) - se il servizio è attivo (operativo o meno)
+ isGeneric: false (boolean, required) - se il servizio è generico
+ category: food (string, required) tipologia di servizio

### ServiceSummaryRes1
+ id: 457 (number, required) - identificatore del servizio
+ shortName: Distributore automatico (string, required) - nome del servizio
+ pic: `distributore_auto` (string, required) - uuid immagine (icona) rappresentante il servizio
+ text: Distributore automaticoServices (string, optional) - descrizione del servizio
+ isActive: true (boolean, required) - se il servizio è attivo (operativo o meno)
+ isGeneric: false (boolean, required) - se il servizio è generico
+ category: food (string, required) tipologia di servizio

### ServiceDetailRes
+ id: 87654321 (number, required) - identificatore del servizio
+ shortName: Punto di ristoro (string, required) - nome del servizio
+ pic: `caffe` (string, required) - icona rappresentante il servizio. E' un id, non indicare l'estensione.
+ text: Caffè, tavola calda (string, optional) - descrizione del servizio
+ isActive: true (boolean, required) - se il servizio è attivo (operativo o meno)
+ isGeneric: false (boolean, required) - se il servizio è generico
+ category: food (string, required) - categoria di appartenenza del servizio
+ agendaId: 12432543 (number, optional) - idenitficatore del calendario riferito al servizio
+ action: (ActionRes)
+ privacyId: 10 (number, required) - privacy richiesta per il servizio
Services

### ActionRes
+ shortName: Carabinieri (string, required) - nome del servizio
+ command: tel (string, required) comando eseguito, tipo di action
+ data: 
    + phone: 118 (string, required) dati associati al comando


### PoiServiceRes
+ id: 1 (number, required) - id Point Of Interest
+ shortName: Cassa 1 (string, required) - nome POI
+ text: Cassa ingresso 1 (string, optional) - descrizione del POI
+ latitude: 23.2 (number, required) - latitudine
+ longitude: 635.2 (number, required) - longitudine
+ level: 2 (number, required) - piano 
+ isAccessible: true (boolean) - accessibilità per invalidi
+ isActive: true (boolean, required) - stato del POI (operativo o meno)
+ creationTS: `2018-11-05T19:04:15.735+0000` (string, required) - data di creazione del POI
+ poiType: 1232 (number, required) - tipologia di POI

### PoiServiceRes1
+ id: 2 (number, required) - id Point Of Interest
+ shortName: Cassa 2 (string, required) - nome POI
+ text: Cassa ingresso 2 (string, optional) - descrizione del POI
+ latitude: 23.2 (number, required) - latitudine
+ longitude: 635.2 (number, required) - longitudine
+ level: 2 (number, required) - piano 
+ isAccessible: true (boolean) - accessibilità per invalidi
+ isActive: true (boolean, required) - stato del POI (operativo o meno)
+ creationTS: `2018-11-05T19:04:15.735+0000` (string, required) - data di creazione del POI
+ poiType: 1232 (number, required) - tipologia di POI

### UserFacility
+ facilityId : (FacilityRes, required) - identificatore facility
+ userId : mario.rossi@utente.it (string, required) - id utente

### NewsRes
+ id: 2 (number, required) - id news
+ shortName: Blocco uscita via Panciatichi (string, required) Titolo
+ text: a causa di interventi stradali (string, optional) Sottotitolo
+ pic: `06d7767b-81ae-480b-849b-0340f9ae1918.jpeg` (string, required) - uuid ad immagine news
+ body: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus fringilla nunc id elementum volutpat. Maecenas at mauris a lorem placerat tincidunt nec id orci. Cras dolor ligula, feugiat sed gravida iaculis, blandit et turpis. Vivamus id rhoncus lorem, id commodo leo. Praesent ornare pretium tortor ac auctor. Phasellus sagittis, massa in mattis tincidunt, massa metus ullamcorper diam, malesuada dapibus magna mauris et enim. Praesent mi quam, volutpat id consectetur sit amet, ullamcorper non ex. Duis dignissim quis ipsum ut pellentesque. Fusce consequat eros vitae erat lobortis elementum. (string, required) Corpo
+ category: (enum[string], required) - categoria
    + Members
        + `DENY`
        + `MUSICA_CLASSICA`
        + `MUSICA_ROCK`


### ToKnow
+ id: 37827387 (string, required) - id della info utile 
+ shortName: ingresso principale aperto (string, required) - 
+ text: apertura ingresso principale (string, optional) - descrizione info da sapere
+ pic: `9f4d310e-4b09-4745-a603-b1f0c83d292f.png` (string, required) - immagine icona di riferimento per la info
+ creationTS: `2018-09-01T10:22:43.235+0000` (string, required) - data generazione della info


### MessagesRes
+ codice: string, required
+ testo: string, required

### SocialNameReq
+ socialName: FACEBOOK (string, required) - nome del social

### CE230Error
- metadata (object)
  - messages (array[230ErrorMessage]) - Lista di messaggi 

### 230ErrorMessage
+ message: Errore validazione input (string, required) - descrizione messaggio
+ title: Validazione input (string, required) - Nome messaggio
+ type: ERROR (string, required) - Tipologia del messaggio
+ target: Modal (string, required) - Tipologia di rappresentazione del messaggio
+ errorCode: 230 (number, required) - Codice di errore

### CEServerError
- metadata (object)
  - messages (array[ServerErrorMessage]) - Lista di messaggi 

### ServerErrorMessage

+ message: GENERAL_ERROR (string, required) - descrizione messaggio
+ title: Errore (string, required) - Nome messaggio
+ type: error (string, required) - Tipologia del messaggio
+ target: Modal (string, required) - Tipologia di rappresentazione del messaggio
+ errorCode: -1 (number, required) - Codice di errore



### EventResDeprecated
+ Rimuovere?
+ id: 78869707 (number, required) - identificatore evento
+ shortName:  Corso di Master in IoT (string, required) - nome evento
+ smallPic: `648521f1-fe15-4408-b489-0cecbcd97e76.png` (string, optional) - uuid immagine (formato piccolo) evento in NAS (Network Attached Storage)
+ bigPic: `4b58bc09-8630-4a8f-ab10-3a230df72369.jpeg` (string, required) - uuid immagine (formato grande) evento in NAS (Network Attached Storage)
+ text: Il corso ha lo scopo di introdurre gli studenti ai seguenti argomenti... (string, required) - descrizione dell'evento
+ isSpot: true (boolean, required) - indica se ha calendario finito (conferenza o concerto)
+ creationTS: `2018-09-01T10:22:43.235+0000` (string, required) - data generazione evento
+ startTS: `2018-09-01T10:22:43.235+0000` (string, required) - data inizio evento (ridondata con Agenda)
+ facilityId: 34323425 (number, required) - identificatore di impianto 
+ pois : (array[PoiEvFacRes, PoiEvFacRes1], required) - poi associati all'evento 
+ services: (array[ServiceSummaryRes, ServiceSummaryRes1], required) - poi associati all'evento 
+ agenda : (AgendaResDeprecated, required) - agenda dell'evento
+ aggregationFields: (array[EventAggregatorRes, EventAggregatorRes1], required) - aggregatori di eventi

### EventResDeprecated1 
+ Rimuovere?
+ id: 98765432 (number, required) - identificatore evento
+ shortName:  Vivi il PIN (string, required) - nome evento
+ smallPic: `5b721f23-650d-408e-bc49-bdfa2f8d7217.png` (string, optional) - uuid immagine (formato piccolo) evento in NAS (Network Attached Storage)
+ bigPic: `6a7ebf2a-f0a9-47fd-8b09-b35ca0100a2b.jpeg` (string, required) - uuid immagine (formato grande) evento in NAS (Network Attached Storage)
+ text: Il corso ha lo scopo di introdurre gli studenti ai seguenti argomenti... (string, required) - descrizione dell'evento
+ isSpot: true (boolean, required) - indica se ha calendario finito (conferenza o concerto)
+ creationTS: `2018-09-01T10:22:43.235+0000` (string, required) - data generazione evento
+ startTS: `2018-09-01T10:22:43.235+0000` (string, required) - data inizio evento (ridondata con Agenda)
+ facilityId: (FacilityRes, required) - impianto
+ pois : (array[PoiEvFacRes, PoiEvFacRes1], required) - poi associati all'evento 
+ services: (array[ServiceSummaryRes, ServiceSummaryRes1], required) - poi associati all'evento 
+ agenda : (AgendaRes1Deprecated, required) - agenda dell'evento
+ aggregationFields : (array[EventAggregatorRes, EventAggregatorRes1], required) - aggregatori di eventi

### AgendaResDeprecated
+ id: 78869708 (number, required) - identificatore del programma
+ startDate: `2018-10-01T00:00:00.000+0000` (string, required) - data (no time) inizio evento
+ endDate: `2018-10-01T00:00:00.000+0000` (string, required) - data (no time) fine evento
+ exception: chiusura straordinaria (string) - eventuale eccezione sul calendario
+ creationTS: `2018-09-01T10:22:43.235+0000` (string, required) - data generazione Agenda 
+ pic : `98e031e9-a3c1-4087-97c3-27bc373a9855.jpeg`  (string, required) - nome file immagine associata
+ fatherId: 12345643 (number, optional) - se exception valorizzata, id agenda a cui è riferita l'eccezione

### AgendaRes1Deprecated
+ id: 12345643 (number, required) - identificatore del programma
+ startDate: "2018-11-11T00:00:00.000+0000" (string, required) - data (no time) inizio evento
+ endDate: `2018-12-24T00:00:00.000+0000` (string, required) - data (no time) fine evento
+ exception: chiusura straordinaria (string) - eventuale eccezione sul calendario
+ creationTS: `2018-09-01T10:22:43.235+0000` (string, required) - data generazione Agenda 
+ pic : `98e031e9-a3c1-4087-97c3-27bc373a9855.jpeg`  (string, required) - nome file immagine associata [TODO: definire formato uuid pic]
+ fatherId: 372676487 (number, optional) - se exception valorizzata, id agenda a cui è riferita l'eccezione